### ISSUE TITLE
Add Support for Ubuntu

### ISSUE THREAD

**Issue by ashishpatel1992** [CodeChefVIT/Engagement-Monitor#18]
Please add support and installation instructions for ubuntu

**Comment by akshatvg** [comment]
@ashishpatel1992 the installation instructions for Ubuntu is the same as MacOS or Linux once you have `pip`. I've edited the README accordingly too.

**Comment by ashishpatel1992** [comment]
Successfully able to setup after installing package `sudo apt-get install libpq-dev`
But on registration page it got stuck after filling details.
Just curios to know if it is trying to send email for verification and got stuck?
If yes is there any way I can setup SMTP for sending email?
